# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbc5746dc94fcb70be2c13727fe14bdc5ecccfc118124be20ad0883514d8a86f368dd01eb32db5db1f3b9b5053e182e8c1f05856e1421eb87c279a9216ae178e

test:
  secret_key_base: ced1d91ecab3809e62d8c0ea8d3192adf9864810ce9ba7e2f1c4bf3bbb7f78754fa32e4a3126acc4bbd53abf883e95adca9b8a1f4e22fd2bd03c2d8445bbee5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
